### ISSUE TITLE
Assets Gathering

### ISSUE THREAD

**Issue by chez14** [sagut-obda/the-game#1]
Dari diskusi kmaren, biar nggak lupa gw bikin issuenya sekarang, aowkaowk bisi ntar ntar ehh kelupaan...

- Lagu
- Model
- Gambar

Kmaren Lagu udah dapet pencerahan, gambar keknya ntar dulu, sama model mau coba pake [Kizuna Ai](https://kizunaai.com/download-page/)? ato sambil ntar jalan aja yak.

Sementara gw assign ke lu dulu, nanti ada update langsung ngontak aja...

Gw sisipin link gdrive grup kita...

https://drive.google.com/drive/folders/0B_WpjF1ked_7WGxVaFdOTzRsZUE?usp=sharing

**Comment by IrvanHardyanto98** [comment]
hmm mungkin boleh dicoba @chez14

**Comment by chez14** [comment]
Finished! YAY!
