### ISSUE TITLE
Main menu

### ISSUE THREAD

**Issue by ferdianexe** [sagut-obda/the-game#2]
untuk pertama main menu isinya start dan exit saja

**Comment by chez14** [comment]
I'm still implementing this, I'll create a new `MainMenuScreenState` and this will be a standard, We're using `(something)ScreenState` for refering to a Screen State, so we dont get confused, or better, we seperate it into a package. What do you think @ferdianexe, @IrvanHardyanto98, and @easydisco?

Anyway, i'll need a Kizuna being posed with strange face if it could, can you help me on it, @Eririn07?

**Comment by chez14** [comment]
This've been done on 25b0946ea652c3217666aa9600e6c2089e257e95.

I'm closing this one.
