### ISSUE TITLE
Enhance si Batunya

### ISSUE THREAD

**Issue by chez14** [sagut-obda/the-game#20]
Si batunya harusnya gerak, yang sekarang dia statis. Berdasarkan kodingannya si Fer nanti gw enchance

**Comment by ferdianexe** [comment]
tips aja kayanya ribet buat mikir OOPnya lagi
segini juga OOPnya udah bagus... menurut gw ga ngerusak aturan manapun
di method ini palingan nanti jangan pake rand.boolean tapi pake rand.int 3 aja
ntar switch case
kalo dia di point ke 3 **VZnya yang diubah** terus ntar di method move check aja nilai znya udah diujung mana kan di singleton udah disediain koordinat batas jalannya jadi ntar pake boolean juga buat nentuin dia jalan ke kiri ato ke kanan
![image](https://user-images.githubusercontent.com/25281200/32983104-325ddfb8-ccc2-11e7-8a33-7145bfdfbc06.png)
semangat chris gw udah cape wkwkkwkw
sekali lagi gw bilang besok ga bisa ngoding
karena exposure

**Comment by ferdianexe** [comment]
oh iya itu kalo misalnya hasil generatenya pohon kodingan yang bounding box itu dibawa juga ya
itu buat hitbox , soalnya di jmonkey kotaknya terlalu gede dan harus dikecilin sampe sekecil itu
well emang harus dikecilin segitunya sih...
soalnya kita maenan koordinatnya kecil kok
area pixel permaenan kita itu -100 sampe 300 aja tapi buat kiri kananya itu cuman 6 pixel :D

**Comment by chez14** [comment]
wkaka thanks tipsnya @ferdianexe, met exposure.

**Comment by ferdianexe** [comment]
Ditutup biar terlihat selesai semuanya XD

**Comment by chez14** [comment]
lol aokwoakwoak
