### ISSUE TITLE
Review from Pa Pascal

### ISSUE THREAD

**Issue by chez14** [sagut-obda/the-game#26]
Todo list:
- Change the `Trump` image xD
- Improve some codes
- Optional: Kizuna, "Hi" pose.. for main menu...
- Find a Game name.
- License

**Comment by ferdianexe** [comment]
License

**Comment by Eririn07** [comment]
resolusi si gambarnya berapa?

**Comment by chez14** [comment]
@Eririn07 mungkin 1440p cukup? kalo kegedean tinggal di kecilin, ato kalo nggak dari background sebelumnya, ukurannya?

**Comment by ferdianexe** [comment]
Btw coba tanyain pa pascal deadline buat revisi game ini gmn ?
kalo masi lama gw mau spare time buat yang lain dlu

**Comment by ferdianexe** [comment]
ada namanya assetMatahari kalo mw liat resolusi si trump~

**Comment by chez14** [comment]
@ferdianexe kalo nggak salah sebelum UAS selesai kayanya, mau di kontakin dulu?

**Comment by ferdianexe** [comment]
kontakin dlu bang :v ini udah UAS kwkwkw
