### ISSUE TITLE
Logical for Memory pooling lantai endless game

### ISSUE THREAD

**Issue by ferdianexe** [sagut-obda/the-game#4]
Logicnya udah dapet...
tapi ga gamungkin toh gambarnya kita buat cuman gitu doang...
jadi kalo bisa nanti kalo ada yang bikin lantainya cepet" kabarin ke gw ,,, ntar gw gabungin disitu.... biar lebih kebayang...

**Comment by chez14** [comment]
Wait, yang gambar gitu doang maksudnya gimana? wkwk

**Comment by ferdianexe** [comment]
Sudah selesai dibahas dan sudah diimplementasi di #13
