### ISSUE TITLE
Tombol menu untuk ngetrigger pause restart dan exit

### ISSUE THREAD

**Issue by ferdianexe** [sagut-obda/the-game#5]

**Comment by chez14** [comment]
Gw barusan nemu buat yang ini barusan, gw listing aja linknya disini, biar ada catetan. (ada beberapa masih relevan, beberapa kagak)

- https://hub.jmonkeyengine.org/t/animation-pause-when-game-paused/31889
- https://hub.jmonkeyengine.org/t/game-menu-and-pause-menu/25459/14
