### ISSUE TITLE
System Scoring

### ISSUE THREAD

**Issue by ferdianexe** [sagut-obda/the-game#8]

**Comment by chez14** [comment]
System scoring, dari yang real di [chrome://dino](chrome://dino), mereka pake perwaktu. Tiap collide baru kita berhenti.

Bahasan yang berhentinya ada di #5...

**Comment by chez14** [comment]
Some Refs for making HUD:

https://jmonkeyengine.gitbooks.io/wiki-jmonkeyengine/advanced/hud.html

**Comment by chez14** [comment]
Based on [HUDGUIState](https://github.com/sagut-obda/the-game/blob/dev-hud-chris/DinoTheGame/src/mygame/state/HUDGuiState.java#L68), the score are always updated by time.

Btw pls review @ferdianexe is this ok enough?

**Comment by chez14** [comment]
Scoring system will be implemented along with #15, should we make a self-managed score, like now or, make a new controller for it @ferdianexe?

**Comment by chez14** [comment]
Ref: 3705621d76ddc72e0bc500dd6541c90cd25f50f5.
